version: "3"
services:
  app:
    container_name: url-shortener
    volumes: 
      - ./:/urlshortener
      - /urlshortener/node_modules
    working_dir: /urlshortener
    environment:
      - NODE_ENV=dev
    # build: https://github.com/semirov/urlshortener.git
    build: .

    depends_on:
      - mongo
    ports:
      - "3000:3000"
    restart: always
    command: npm run dev
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
      #  - ./data:/data/db
    ports:
      - "27017:27017"