version: "3"
services:
  app:
    container_name: url-shortener
    working_dir: /urlshortener
    env_file: env.list
    environment:
      NODE_ENV: production

    restart: always
    command: npm start
    build: https://github.com/semirov/urlshortener.git
    ports: 
      - "80:80"